kind: Pod
apiVersion: v1
metadata:
  name: annotations
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: DEVOPS
        - name: topic
          value: Kubernetes 