kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: chandu
            
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         name: chandu
      #         key: course
      #   - name: topic
      #     valueFrom:
      #       configMapKeyRef:
      #         name: chandu
      #         key: topic