apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.49.240-192.168.49.250

---

kind: Pod
apiVersion: v1
metadata:
  namespace: metallb-system
  name: nginx
  labels:
    name: frontend
    project: expese
    component: frontend
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
---

kind: Service
apiVersion: v1 
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    name: frontend
    project: expese
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80