kind: Service
apiVersion: v1 
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expese
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32750