kind: Service
apiVersion: v1 
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    name: frontend
    project: expese
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31755