apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep it as Always
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
